name: Build and Release Yet Another Driver Station

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a new release'
        required: false
        default: false
        type: boolean

env:
  QT_VERSION: '6.5.3'
  CMAKE_VERSION: '3.21.0'

jobs:
  # Skip builds for draft PRs
  check-draft:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    outputs:
      is_draft: ${{ steps.check.outputs.is_draft }}
    steps:
      - name: Check if PR is draft
        id: check
        run: |
          if [ "${{ github.event.pull_request.draft }}" = "true" ]; then
            echo "is_draft=true" >> $GITHUB_OUTPUT
            echo "Skipping build for draft PR"
          else
            echo "is_draft=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: [check-draft]
    if: always() && (github.event_name != 'pull_request' || needs.check-draft.outputs.is_draft == 'false')
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            qt_arch: win64_msvc2019_64
            cmake_preset: windows-release
            artifact_name: YetAnotherDriverStation-Windows
          - os: ubuntu-latest
            qt_arch: gcc_64
            cmake_preset: linux-release
            artifact_name: YetAnotherDriverStation-Linux
          - os: macos-latest
            qt_arch: clang_64
            cmake_preset: macos-release
            artifact_name: YetAnotherDriverStation-macOS

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Clone QHotkey
      run: |
        git clone --depth 1 https://github.com/Skycoder42/QHotkey.git thirdparty/QHotkey

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        arch: ${{ matrix.qt_arch }}
        cache: true
        modules: 'qtnetworkauth qtmultimedia'

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev libgl1-mesa-dev libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0

    - name: Setup MSVC (Windows)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DENABLE_GLOBAL_SHORTCUTS=ON -DENABLE_FMS_SUPPORT=ON -DENABLE_GLASS_INTEGRATION=ON -DENABLE_DASHBOARD_MANAGEMENT=ON -DENABLE_PRACTICE_MATCH=ON

    - name: Build
      run: |
        cmake --build build --config Release --parallel

    - name: Package (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir -p package
        cp build/YetAnotherDriverStation package/
        cp -r dashboards package/
        tar -czf ${{ matrix.artifact_name }}.tar.gz -C package .

    - name: Package (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir package
        copy build\Release\YetAnotherDriverStation.exe package\
        xcopy dashboards package\dashboards\ /E /I
        windeployqt package\YetAnotherDriverStation.exe --qmldir qml
        7z a ${{ matrix.artifact_name }}.zip package\*

    - name: Package (macOS)
      if: runner.os == 'macOS'
      run: |
        mkdir -p package
        cp -r build/YetAnotherDriverStation.app package/
        cp -r dashboards package/YetAnotherDriverStation.app/Contents/Resources/
        macdeployqt package/YetAnotherDriverStation.app -qmldir=qml
        tar -czf ${{ matrix.artifact_name }}.tar.gz -C package .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          ${{ matrix.artifact_name }}.tar.gz
          ${{ matrix.artifact_name }}.zip
        retention-days: 30

  # Comment on PR with download links
  pr-comment:
    needs: [build]
    if: github.event_name == 'pull_request' && !failure() && !cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr_number = context.payload.pull_request.number;
            const run_id = context.runId;
            
            const comment = `## 🚀 Build Artifacts Ready!
            
            Your PR has been built successfully across all platforms. Download the artifacts to test your changes:
            
            ### Download Links
            - [Windows Build](https://github.com/${owner}/${repo}/actions/runs/${run_id})
            - [macOS Build](https://github.com/${owner}/${repo}/actions/runs/${run_id})
            - [Linux Build](https://github.com/${owner}/${repo}/actions/runs/${run_id})
            
            **Note:** Artifacts are available for 7 days. Click the links above to access the GitHub Actions page and download the artifacts.
            
            ### Testing Checklist
            Please test the relevant configurations for your changes:
            - [ ] Windows functionality
            - [ ] macOS functionality  
            - [ ] Linux functionality
            - [ ] Robot communication
            - [ ] Emergency stop functionality
            - [ ] Global shortcuts (Space, Enter, Ctrl+E)
            - [ ] Controller detection
            - [ ] Feature flags work as expected
            `;
            
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr_number,
              body: comment
            });

  # Create release if this is a tag push
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          YetAnotherDriverStation-Linux/*.tar.gz
          YetAnotherDriverStation-Windows/*.zip
          YetAnotherDriverStation-macOS/*.tar.gz
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
